import { Player } from './player';

export const PLAYERS: Player[] = [
  {
    id: 11,
    name: 'A Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 12,
    name: 'B Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 13,
    name: 'C Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 14,
    name: 'D Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 15,
    name: 'E Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 16,
    name: 'F Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 17,
    name: 'G Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 18,
    name: 'H Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 19,
    name: 'I Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 20,
    name: 'J Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 21,
    name: 'K Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 22,
    name: 'L Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 23,
    name: 'M Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 24,
    name: 'N Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 25,
    name: 'O Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 26,
    name: 'P Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
  {
    id: 27,
    name: 'Q Player',
    resolve: 2000,
    potency: 100,
    hp: 300,
    show: false,
    online: false,
  },
];
